wepublish/wepublish

- examples/website/src/shared/utility.ts
- packages/editor/src/client/blocks/embeds/iframe.tsx
- packages/editor/src/client/utility.ts
see #27 and closes #27 after merge
> drop white space removal

- packages/api/src/graphql/permissions.ts
> Add delete token permission to AllPermissions

- packages/editor/src/client/routes/authorList.tsx
#74 
Fixed the bug where the author list was not automatically updated when an author was deleted.
Seems to be a bug related to Apollo, so the refetch after a delete might not be needed in the future for newer versions of Apollo for React.
> Bug fix - Author list now updates the UI after an author is removed

- packages/api/__tests__/api/private/index.ts
- packages/api/__tests__/api/private/page.graphql
- packages/api/__tests__/specs/__snapshots__/page.ts.snap
- packages/api/__tests__/specs/page.ts
API Page tests for CRUD + publish, unpublish
> test(api): api page tests

- packages/editor/src/client/routes/navigationList.tsx
Analogous to all other list views.
Let me know if this as expected 🥂
> Align new navigation button to the right (#84)

- packages/api-db-mongodb/src/db/invoice.ts
- packages/api/src/context.ts
- packages/api/src/db/invoice.ts
- packages/api/src/error.ts
- packages/api/src/graphql/invoice.ts
- packages/api/src/graphql/mutation.public.ts
- packages/api/src/graphql/query.public.ts
- packages/api/src/graphql/user.ts
This PR introduces the possibility for authenticated members to update their own profile and subscription.
⚠️ this PR merges into `f/WEP-23-create-member-plan`
> Edit user and subscription through public

- examples/api/src/index.ts
- packages/api/src/error.ts
- packages/api/src/graphql/mutation.public.ts
This PR adds some minor functionality before the release
> Fixes for the next release

- packages/api-db-mongodb/src/db/comment.ts
- packages/api/src/graphql/comment.ts
- packages/api/src/graphql/query.private.ts
fixed pagination and added sorting in "Get Comments" private queries
> fixed pagination and sort

- packages/api-db-mongodb/src/db/article.ts
- packages/api-db-mongodb/src/db/page.ts
- packages/api/src/graphql/query.private.ts
- packages/editor/src/client/api/article.graphql
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/api/page.graphql
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/routes/articleList.tsx
- packages/editor/src/client/routes/pageList.tsx
This PR introduces pagination to the pageList and articleList in the editor.
> Pagination for article and page lists

- packages/api/src/graphql/mutation.public.ts
bug fix for master which is already on the release branch.
> fix updateUser and updateSubscription mutations

- packages/editor/src/client/login.tsx
Allows user to submit login credentials with enter key.
> wpc-220 login with enter

- packages/api-db-mongodb/src/db/article.ts
- packages/api-db-mongodb/src/db/schema.ts
- packages/api/src/db/article.ts
- packages/api/src/graphql/article.ts
- packages/editor/src/client/api/article.graphql
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/articleMetadataPanel.tsx
- packages/editor/src/client/panel/publishArticlePanel.tsx
- packages/editor/src/client/routes/articleEditor.tsx
Fixex WPC-223. This PR adds a new Field SEO Title to the article metadata and use it to create the slug.
> Added a new seoTitle field to the article metadata

- examples/website/src/shared/blocks/richTextBlock/editor/render.tsx
WPC-265. added table border color to the website again.
> Added color to the table in the example website

- packages/editor/src/client/panel/articleMetadataPanel.tsx
WPC-278. This bug fix ensures that already selected authors stay selected even if they are not in the search results.
> Selected authors stay selected during search

- packages/editor/src/client/routes/articleList.tsx
WPC-289: fix column width: In Article List extended the default width of the States column so that content is displayed.
> fix table column width

- FAQ.md
During the installation of wepublish I encountered a bunch of errors. To make it easier for my successors, I have included the errors and their solution in the FAQ.
> enh. installation troubleshooting documentation

- packages/editor/src/client/panel/navigationEditPanel.tsx
This adds spacing between the input in the Navigation panel.
> add spacing to layout of forms in Navigation panel

- packages/editor/src/client/routes/articleList.tsx
- packages/editor/src/client/routes/pageList.tsx
> added time in modefied coloumn

- packages/editor/src/client/global.less
- packages/editor/src/client/routes/commentList.tsx
WPC-340: Highlight color on comment table reflects the status of the comment state.
> Comment list color

- packages/editor/src/client/global.less
WPC-340: Update comment list so rows are colored without hover.
> Color all rows on comment table

- examples/website/src/shared/atoms/polisEmbed.tsx
- examples/website/src/shared/blocks/blockRenderer.tsx
- examples/website/src/shared/blocks/embedBlock.tsx
- examples/website/src/shared/route/articleTemplateContainer.tsx
- examples/website/src/shared/route/blockAdapters.ts
- examples/website/src/shared/route/gqlFragments.ts
- examples/website/src/shared/route/pageTemplateContainer.tsx
- examples/website/src/shared/types.ts
- packages/api/__tests__/api/private/index.ts
- packages/api/__tests__/api/public/index.ts
- packages/api/src/db/block.ts
- packages/api/src/graphql/blocks.ts
- packages/editor/src/client/api/block.graphql
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/blocks/embedBlock.tsx
- packages/editor/src/client/blocks/embeds/polis.tsx
- packages/editor/src/client/blocks/types.ts
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/embedEditPanel.tsx
WPC-215: Add Polis embed block
> Add polis embed block

- packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
WPC-325: change placement of date picker inside deactivate user subscription
> placement of date picker in user subscription panel

- packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
- packages/editor/__tests__/specs/peerEditPanel.tsx
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/peerEditPanel.tsx
- packages/editor/src/client/routes/peerList.tsx
WPC-22: Disable peering to host
> validation for url peering to host

- packages/editor/__tests__/specs/__snapshots__/tokenGeneratePanel.tsx.snap
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/tokenGeneratePanel.tsx
WPC-409: Notification warning on token generate panel that tokens cannot be retrieved.
> token save notification

- packages/api/src/utility.ts
This PR is an addition to the PR https://github.com/wepublish/wepublish/pull/281. It also handles PeerArticleTeaser and PageTeaser.
> reverse enums also for PeerArticleTeasers and PageTeasers

- packages/editor/src/client/routes/articleEditor.tsx
- packages/editor/src/client/routes/pageEditor.tsx
Re-align text to left on page and article editor
> remove align text center

- examples/api/src/index.ts
- examples/website/src/shared/route/pageTemplateContainer.tsx
- packages/api/__tests__/specs/__snapshots__/user.ts.snap
- packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
- packages/api/__tests__/utility.ts
- packages/api/src/graphql/permissions.ts
- packages/api/src/graphql/query.private.ts
- packages/api/src/graphql/query.public.ts
- packages/api/src/urlAdapter.ts
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/api/page.graphql
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/pagePreviewLinkPanel.tsx
- packages/editor/src/client/routes/pageList.tsx
WPC-354. This PR allows to create preview links with JWT for pages.
> Preview links for pages

- packages/api/src/graphql/richText.ts
Extending API Rich Text Elements with more new elements we now support.
> Extending elements in API

- packages/editor/src/client/panel/userEditPanel.tsx
> mapping metadata properties to get rid of __typename

- packages/editor/src/client/panel/publishArticlePanel.tsx
- packages/editor/src/client/panel/publishPagePanel.tsx
WPC-566: Set date picker to open to most recent pending publication date.
> initialize calendar with last publication date

- examples/website/src/shared/atoms/bildwurfAdEmbed.tsx
- examples/website/src/shared/blocks/embedBlock.tsx
- examples/website/src/shared/route/articleTemplateContainer.tsx
- examples/website/src/shared/route/blockAdapters.ts
- examples/website/src/shared/route/gqlFragments.ts
- examples/website/src/shared/route/pageTemplateContainer.tsx
- examples/website/src/shared/types.ts
- packages/api/src/db/block.ts
- packages/api/src/graphql/blocks.ts
- packages/editor/src/client/api/block.graphql
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/blocks/embedBlock.tsx
- packages/editor/src/client/blocks/embeds/bildwurfAd.tsx
- packages/editor/src/client/blocks/types.ts
- packages/editor/src/client/panel/embedEditPanel.tsx
WPC-530. This PR adds a new embed block for bildwurf ads.
> new block for bildwurf ads

- packages/api-db-mongodb/src/tsconfig.json
- packages/api/package.json
- packages/api/src/server.ts
- packages/api/src/tsconfig.json
- yarn.lock
This PR updates apollo-server-express in the api to version 2.25.3
> updated apollo-server-express to 2.25.3

- package.json
Remove directory instead of running dev yarn command on external container.
> Bug(media): Fix `clean:media` command

- packages/api/src/payments/payrexxPaymentProvider.ts
Implements https://github.com/wepublish/wepublish/issues/437
> Add invoice email to payrexx create gateway request

- packages/editor/src/client/api/index.ts
> Updated editor graphql codegen api

- packages/api/src/mails/MailgunMailProvider.ts
Mailgun API calls didn't use https
> make the mailgun from.submit use https

- packages/api/src/payments/payrexxPaymentProvider.ts
>  encode all url parameters that are sent with node-fetch

- packages/api/src/memberContext.ts
> only send custom_missing mail to offSession payments

- packages/editor/src/client/locales/de.json
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/locales/fr.json
#446
Hi @tomaszdurka @roosnic1 @michael-scheurer , could you have a look at this pull request ?
I think this is it -> the bug but I haven't test because i don't have 'Payment Adapter' to choose when I create 'Payment Method'
> Fix typos in i18n

- packages/api/src/graphql/mutation.private.ts
WPC-616: Fixed duplicate article/page mutation to include pending.
> duplicate pending article/page

- packages/api-db-mongodb/src/db/article.ts
- packages/api-db-mongodb/src/db/page.ts
- packages/editor/src/client/panel/publishArticlePanel.tsx
- packages/editor/src/client/panel/publishPagePanel.tsx
- packages/editor/src/client/routes/articleEditor.tsx
- packages/editor/src/client/routes/pageEditor.tsx
This PR fixes some tiny but essential things for the 3.0.0 release.
> release 3.0.0 hot fixes

- packages/api/src/memberContext.ts
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/panel/peerProfileEditPanel.tsx
- packages/editor/src/client/routes/peerList.tsx
- Link to website added on peer profile info
> preview own peer profile

- packages/api/src/graphql/memberPlan.ts
- packages/editor/src/client/panel/memberPlanEditPanel.tsx
- removed nonNull array in graphQL so tags can be empty
-  panel edit to be able to read empty tags
> bug fix in memberplans

- examples/api/nodemon.json
- examples/api/src/index.ts
- packages/api-db-mongodb/src/db/subscription.ts
- packages/api-db-mongodb/src/db/user.ts
- packages/api/src/db/subscription.ts
- packages/api/src/db/tempUser.ts
- packages/api/src/db/user.ts
- packages/api/src/events.ts
- packages/api/src/graphql/invoice.ts
- packages/api/src/graphql/mutation.private.ts
- packages/api/src/graphql/mutation.public.ts
- packages/api/src/graphql/subscription.ts
- packages/api/src/memberContext.ts
- packages/api/src/payments/paymentProvider.ts
- packages/api/src/payments/payrexxPaymentProvider.ts
- packages/api/src/utility.ts
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/locales/de.json
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/locales/fr.json
- packages/editor/src/client/routes/subscriptionList.tsx
- packages/editor/src/client/utility.ts
fixes some bugs in multiple subscriptions:
- error when calling cancelUserSubscription mutation
- creates invoice when adding a new user subscription via editor.
> WIP: fix bugs in multiple subscriptions

- packages/editor/__tests__/specs/i18n.test.tsx
- packages/editor/src/client/i18n.ts
- packages/editor/src/client/index.tsx
Just a little cleanup of a side effect when importing a script. Moved the same content into an initializer and fixed a small typo in a comment 😄
> refactor(editor): eliminate side effect when importing i18n

- packages/api/src/db/subscription.ts
- packages/api/src/graphql/subscription.ts
This PR fixes the sorting for the subscriptions query.
> fix sorting for subscriptions query

- packages/editor/src/client/locales/rsuiteDe.ts
- packages/editor/src/client/locales/rsuiteFr.ts
- packages/editor/src/client/routes/articleList.tsx
- packages/editor/src/client/routes/authorList.tsx
- packages/editor/src/client/routes/commentList.tsx
- packages/editor/src/client/routes/imageList.tsx
- packages/editor/src/client/routes/pageList.tsx
- packages/editor/src/client/routes/peerArticleList.tsx
- packages/editor/src/client/routes/subscriptionList.tsx
- packages/editor/src/client/routes/userList.tsx
- packages/editor/src/client/utility.ts
> fix(editor): pagination translation broken and max pages

- docs/README.md
> documentation for validation

- .vscode/extensions.json
1. Eslint
2. Prettier
3. Kubernetes
4. Docker
5. Regex previewer/tester
6. Jest runner (allows to run a single test, suite etc. via a click or run it in debug mode)
7. Markdown previewer
8. Adds mermaid support to Markdown (diagrams via Markdown, supported by Github)
> chore: add recommended vscode plugins

- .github/workflows/release-helm-chart.yml
- helm/charts/website/Chart.yaml
- helm/charts/website/templates/_helpers.tpl
- helm/charts/website/templates/deployment.yaml
- helm/charts/website/templates/ingress.yaml
- helm/charts/website/templates/secrets.yaml
- helm/charts/website/templates/service.yml
- helm/charts/website/values.yaml
- Add website helm chart
- Add helm chart for website
> Ad website helm chart

- CHANGELOG.md
- examples/api/package.json
- examples/api/src/index.ts
- lerna.json
- packages/api/package.json
- packages/editor/package.json
- packages/oauth2/package.json
* `api`
* [#702](https://github.com/wepublish/wepublish/pull/702) WPC-696 integrate payrexx subscription provider ([@elias-summermatter](https://github.com/elias-summermatter))
* `api`, `editor`
* [#708](https://github.com/wepublish/wepublish/pull/708) feat(api): user votes/rating api ([@Itrulia](https://github.com/Itrulia))
* [#706](https://github.com/wepublish/wepublish/pull/706) feat(api/editor): implement comment and poll blocks ([@Itrulia](https://github.com/Itrulia))
* [#694](https://github.com/wepublish/wepublish/pull/694) feat(api/editor): implement a comment rating system ([@Itrulia](https://github.com/Itrulia))
* `api`
* [#715](https://github.com/wepublish/wepublish/pull/715) Fix payment provider period start date ([@elias-summermatter](https://github.com/elias-summermatter))
* …
> Release 7.1.0

- packages/api/prisma/migrations/20221025091043_revisions_image_references/migration.sql
- packages/api/prisma/schema.prisma
author ids will come next
Related to your work @penk85
> feat(api): add relations to revision images

- yarn.lock
see https://github.com/babel/babel/issues/14587#issuecomment-1137304259
> build: fix babel error by updating @babel/types

- packages/api/prisma/migrations/20221027113732_article_revisions_author_references/migration.sql
- packages/api/prisma/schema.prisma
- packages/api/src/context.ts
- packages/api/src/db/article.ts
- packages/api/src/graphql/article.ts
- packages/api/src/graphql/article/article.private-mutation.ts
- packages/api/src/graphql/article/article.public-queries.ts
- packages/api/src/graphql/article/article.queries.ts
also changed social media authors also to be hidden when hideAuthors is true (talked with Laurent about it
> fix(api): authors being in a correct relational database structure

- packages/api/__tests__/api/private/index.ts
- packages/api/__tests__/api/public/index.ts
Regenerating test api definitions went missing and I guess the merge didn't happen through CI
> fix: regenerated api test definitions

- packages/editor/src/client/panel/imageEditPanel.tsx
react router update is probably the cause, since the imageurl is an external url it should use a simple  tag
> fix(editor): image url wrong

- packages/editor/src/client/atoms/imageMetaData.tsx
ignore metadata of images not supported by exifr
> fix(editor): gif or other unsupported images by exfir upload broken

- .github/workflows/main.yml
- .github/workflows/pr_close.yml
> ci: fix permissions missing for GA

- packages/api/__tests__/api/private/index.ts
- packages/api/src/graphql/page.ts
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/blocks/teaserGridBlock.tsx
- packages/editor/src/client/panel/pageMetadataPanel.tsx
- packages/editor/src/client/panel/teaserEditPanel.tsx
- packages/editor/src/client/routes/pageEditor.tsx
Not a breaking change as just private api
> fix(api): slugs and titles of pages to be nullable

- packages/api/__tests__/api/private/index.ts
- packages/api/__tests__/specs/__snapshots__/event.ts.snap
- packages/api/__tests__/specs/event.ts
- packages/api/src/context.ts
- packages/api/src/db/block.ts
- packages/api/src/graphql/blocks.ts
- packages/api/src/graphql/event/event.private-mutation.ts
- packages/api/src/graphql/event/event.queries.ts
- packages/api/src/graphql/event/event.ts
- packages/api/src/graphql/mutation.private.ts
- packages/editor/src/client/api/block.graphql
- packages/editor/src/client/api/index.ts
- packages/editor/src/client/atoms/tag/selectTags.tsx
- packages/editor/src/client/blocks/blockMap.tsx
- packages/editor/src/client/blocks/eventBlock.tsx
- packages/editor/src/client/blocks/types.ts
- packages/editor/src/client/locales/de.json
- packages/editor/src/client/locales/en.json
- packages/editor/src/client/locales/fr.json
- packages/editor/src/client/panel/selectEventsPanel.tsx
- packages/editor/src/client/routes/events/eventCreateView.tsx
- packages/editor/src/client/routes/events/eventEditView.tsx
Similar to the comment block
Also added filter for tags
> feat(editor/api): implemented the event block

- packages/editor/src/client/blocks/eventBlock.tsx
- packages/editor/src/client/blocks/types.ts
- packages/editor/src/client/routes/events/eventListView.tsx
> feat(editor): improve event preview

- apps/editor/src/app/atoms/searchAndFilter/userSearch.tsx
Was broken because of a merge of mine
> fix(editor): user select broken

- apps/editor/src/app/atoms/searchAndFilter/userSearch.tsx
- apps/editor/src/app/panel/userCheckPicker.tsx
> fix(editor): user filter being wrong after graphql changes

- libs/consent/api/setup-database.js
- libs/membership/api/setup-database.js
> test(membership-api): fix testing db name

- apps/editor/src/app/routes/imageList.tsx
@penk85 
- 5 items per row
- hovering on image doesn't make content jump
- title displayed on image is readable (add bg  under text)
- increase the size of images a little bit
> small fixes for grid view

- helm/charts/wepublish/Chart.yaml
- helm/charts/wepublish/templates/api.yaml
- helm/charts/wepublish/templates/editor.yaml
- helm/charts/wepublish/templates/website.yaml
- Allow merging "envs" with the same variables
- Bump chart to 2.0.1
> Allow same variables on deployment and app-specific envs

- apps/editor/src/app/atoms/dateTimePicker.tsx
WPC-1165: align timepicker with datepicker.
> timepicker alignment

- libs/events/import/api/src/index.ts
- libs/events/import/api/src/lib/events-import.module.ts
- libs/events/import/api/src/lib/import/agenda-basel.service.spec.ts
- libs/events/import/api/src/lib/import/agenda-basel.service.ts
- libs/events/import/api/src/lib/import/kulturagenda-parser.ts
- libs/image/api/src/index.ts
- libs/image/api/src/lib/image-fetcher/image-fetcher.module.ts
- libs/image/api/src/lib/image-fetcher/image-fetcher.service.ts
@antkiewiczk I also saw there's no test for the parser itself and the `importedEvent` tests don't do anything because the method itself is mocked away.
> refactor(events-import-api): some restructuring

- apps/website-example/pages/a/[id]/[slug].tsx
- apps/website-example/pages/a/[id]/index.tsx
- apps/website-example/pages/author/[slug].tsx
- apps/website-example/pages/author/index.tsx
- apps/website-example/pages/events/[id].tsx
- apps/website-example/pages/p/[peerId]/[articleId].tsx
- apps/website-example/pages/page/[id]/[slug].tsx
- apps/website-example/pages/page/[id]/index.tsx
- apps/website-example/src/next-wepublish-link.tsx
- libs/website/api-v2/src/lib/client.tsx
- libs/website/api/src/lib/client.tsx
- libs/website/api/src/lib/graphql.ts
- libs/website/api/src/lib/schemas/author.graphql
Also:
1. Removed onVariablesChange from author list as it was not used
2. Added sort and order that was missing from author list
3. Added SSR to single author view
4. Changed fallback: true to fallback: 'blocking', as the router params were undefined to start with
> feat(website): add apollo cache for SSR

- .github/workflows/on-master-push-git-tag.yml
- Remove pull-request executiins
> Do not execute tag-push on pull-request

- .gitignore
- bin/release-alpha.sh
- Push to branch when checking out first time
- Add .c
> chore(releases): improve release scripts with Github actions

- .github/workflows/on-pr-review.yml
> chore(reviews): Make sure there is no volume attached to media-server, use newest chart 1.0.6

- apps/bajour/src/components/bajour/archive/archive-slider.tsx
- apps/bajour/src/components/bajour/archive/archive.tsx
1. Changed the slider to use custom rendering -> no more !important
2. Changed to use grid-areas for no more empty divs
3. Some slight styling changes
> refactor(bajour): my feedback for the bajour archive

- docker/migrate_start.sh
> fix(migrations): Fix migraton command, so it fails if one of subcommands fails

- apps/bajour/src/components/bajour/briefing/basel-briefing.tsx
- apps/bajour/src/components/website-builder-styled/blocks/teaser-grid-styled.tsx
- apps/bajour/src/styles/theme.ts
- libs/article/website/src/lib/__snapshots__/article-container.spec.tsx.snap
- libs/article/website/src/lib/__snapshots__/article.spec.tsx.snap
- libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
- libs/block-content/website/src/lib/embed/__snapshots__/embed-block.spec.tsx.snap
- libs/block-content/website/src/lib/embed/embed-block.tsx
- libs/page/website/src/lib/__snapshots__/page-container.spec.tsx.snap
- libs/page/website/src/lib/__snapshots__/page.spec.tsx.snap
Also don't forward aspect ratio to HTML in the EmbedBlock
> fix(bajour): theme breakpoints not working & styling for xl

- apps/gruppetto/pages/_app.tsx
- package-lock.json
- package.json
This adds the Google Analytics script to all pages.
> GRUP-2: Add Google Analytics script

- apps/editor/__tests__/specs/__snapshots__/subscriptionEditView.test.tsx.snap
- apps/editor/__tests__/specs/subscription-mocks/invoices.mock.json
- apps/editor/__tests__/specs/subscription-mocks/memberplanlist.mock.json
- apps/editor/__tests__/specs/subscription-mocks/paymentmethodlist.mock.json
- apps/editor/__tests__/specs/subscription-mocks/renewsubscription.mock.json
- apps/editor/__tests__/specs/subscription-mocks/userlist.mock.json
- apps/editor/__tests__/specs/subscriptionEditView.test.tsx
- apps/editor/src/app/locales/de.json
- apps/editor/src/app/locales/en.json
- apps/editor/src/app/locales/fr.json
- apps/editor/src/app/routes/subscriptions/subscriptionEditView.tsx
- libs/api/__tests__/api/private/index.ts
- libs/api/__tests__/specs/subscription.test.ts
- libs/api/src/lib/graphql/mutation.private.ts
- libs/api/src/lib/graphql/subscription/subscription.private-mutation.ts
- libs/editor/api/src/lib/graphql.ts
- libs/editor/api/src/lib/schemas/subscription.graphql
This change adds a button to the subscription form in the editor that allows administrators to renew an existing subscription. The renewal always spans one period of the subscription. It can subsequently be marked as manually paid in the editor.
> SHARE-10: Renew subscriptions in editor

- apps/babanews/pages/signup.tsx
- apps/bajour/pages/signup.tsx
- apps/bajour/src/components/website-builder-overwrites/blocks/comment-list-container/comment-list-container-fdt.tsx
- apps/gruppetto/pages/signup.tsx
- apps/website-example/pages/signup.tsx
- libs/authentication/website/src/lib/login-form/login-form-container.tsx
- libs/comments/website/src/lib/comment-editor/__snapshots__/comment-editor.spec.tsx.snap
- libs/comments/website/src/lib/comment-editor/comment-editor.spec.tsx
- libs/comments/website/src/lib/comment-editor/comment-editor.tsx
- libs/comments/website/src/lib/comment-list/__snapshots__/comment-list-container.spec.tsx.snap
- libs/comments/website/src/lib/comment-list/__snapshots__/comment-list-item.spec.tsx.snap
- libs/comments/website/src/lib/comment-list/__snapshots__/comment-list.spec.tsx.snap
- libs/comments/website/src/lib/comment-list/comment-list-item.tsx
- libs/website/builder/src/lib/comment.interface.ts
- libs/website/builder/src/lib/container.interface.ts
This reverts commit 3771d8b3dd4070816286137eac81cd0f31f8eb1b.
> Revert "BA-148: Login while commenting (#1392)"

- README.md
Small correction for the README
> Change node version to 18 in README

- libs/article/website/src/lib/__snapshots__/article-container.spec.tsx.snap
- libs/article/website/src/lib/__snapshots__/article.spec.tsx.snap
- libs/article/website/src/lib/article-list/__snapshots__/article-list-container.spec.tsx.snap
- libs/article/website/src/lib/article-list/__snapshots__/article-list.spec.tsx.snap
- libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-grid-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-grid-flex-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-list-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/teaser.tsx
- libs/page/website/src/lib/__snapshots__/page-container.spec.tsx.snap
- libs/page/website/src/lib/__snapshots__/page.spec.tsx.snap
to
Checked Bajour (as they use custom teasers) and everything was alright
> refactor(block-content-website): teaser images smaller + bigger text

- apps/tsri/pages/_app.tsx
- apps/tsri/src/components/tsri-navbar.tsx
- libs/navigation/website/src/lib/navbar/__snapshots__/navbar-container.spec.tsx.snap
- libs/navigation/website/src/lib/navbar/__snapshots__/navbar.spec.tsx.snap
- libs/navigation/website/src/lib/navbar/navbar.tsx
Logo is now properly centered independent on actions/header length on tablet/desktop, on mobile it goes next to the menu button.
> feat(tsri/navigation-website): refactor navigation & add subscribe button to tsri

- apps/api-example/prisma/seed.ts
- apps/api-example/project.json
- apps/media/src/app/app.controller.ts
- apps/media/src/bootstrap.ts
- apps/media/src/main.ts
- libs/api/prisma/seed.ts
- libs/api/src/lib/media/novaMediaAdapter.ts
- libs/media/api/src/lib/media-service/supported-images-validator.ts
- package.json
The upload is now timing out, rest works
> fix(api-example): seeding of images

- apps/mannschaft/src/theme.tsx
- libs/article/website/src/lib/__snapshots__/article-container.spec.tsx.snap
- libs/article/website/src/lib/__snapshots__/article.spec.tsx.snap
- libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-grid-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-grid-flex-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser-list-block.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/__snapshots__/teaser.spec.tsx.snap
- libs/block-content/website/src/lib/teaser/teaser.tsx
- libs/navigation/website/src/lib/navbar/navbar.tsx
- libs/page/website/src/lib/__snapshots__/page-container.spec.tsx.snap
- libs/page/website/src/lib/__snapshots__/page.spec.tsx.snap
Also fixed a bug with teaser pre titles & navbar
> refactor(mannschaft): changed colors for mannschaft

- libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
- libs/block-content/website/src/lib/block-styles/teaser-slider/__snapshots__/teaser-slider.spec.tsx.snap
- libs/block-content/website/src/lib/block-styles/teaser-slider/teaser-slider.tsx
- libs/block-content/website/src/lib/teaser/teaser.tsx
has no affect on layout as parent is not a grid, but causes the condition to not make the font sizes bigger
> fix(block-content-website): teaser slider having teaser styles too big

- apps/mannschaft/src/mannschaft-block-renderer.tsx
- apps/mannschaft/src/mannschaft-page.tsx
Also added correct colors to slider
> feat(mannschaft): make break blocks more seamless

- apps/editor/src/app/locales/de.json
- apps/editor/src/app/locales/en.json
- apps/editor/src/app/locales/fr.json
- libs/richtext/api/src/lib/richtext-scalar.ts
- libs/richtext/website/src/lib/render-element.tsx
- libs/ui/editor/src/lib/blocks/richTextBlock/toolbar/linkMenu.tsx
- libs/website/src/lib/website.provider.tsx
- Allow to save ids on links
- Implement anchors
> feat(website/editor): Allow anchors

- .env
- apps/babanews/next.config.js
- apps/bajour/next.config.js
- apps/gruppetto/next.config.js
- apps/mannschaft/next.config.js
- apps/mannschaft/pages/_app.tsx
- apps/tsri/next.config.js
- apps/website-example/next.config.js
> ci: dont run bundle analyzer on CI/CD

- apps/bajour/src/components/website-builder-overwrites/banner/bajour-banner.tsx
- libs/banner/website/src/lib/banner.tsx
This changes how the cta property of the banner works. When a cta is defined, it is hidden when the banner is maximized, and is only shown when the banner is minimized.
That means, if the banner is maximized, the title, the text, and all buttons are shown.
If the banner is minimized, the CTA and the primary button are shown.
> BA-33: Change CTA behaviour

- apps/api-example/schema-v2.graphql
- apps/editor/src/app/routes/polls/PollVotesListContainer.tsx
- libs/api/__tests__/api/public/index.ts
- libs/editor/api-v2/src/lib/graphql.ts
- libs/editor/api-v2/src/lib/schemas/polls.graphql
- libs/migrate-wordpress/src/api/public/index.ts
- libs/poll/api/src/lib/poll-vote.model.ts
- libs/poll/api/src/lib/poll-vote.resolver.ts
- libs/poll/api/src/lib/poll-vote.service.ts
- libs/ui/editor/src/lib/hooks/use-loader.tsx
- libs/website/api/src/lib/graphql.ts
- feat(polls): Delete many poll votes in single mutation
- chore(ui): WrapLoading: Remove loader regardless of the promise result
> feat(polls): Delete poll votes in batch

- apps/bajour/src/components/website-builder-overwrites/banner/bajour-banner.tsx
- libs/banner/website/src/lib/banner.tsx
- libs/navigation/website/src/lib/navbar/navbar.tsx
This changes the banner to scroll with the page content.
> BA-33: Make the banner scroll with the content of the page

- apps/mannschaft/.eslintrc.json
- apps/mannschaft/pages/_app.tsx
- apps/mannschaft/public/OneSignalSDKWorker.js
- package-lock.json
- package.json
This adds push notifications via OneSignal to the Mannschaft website.
> MAN-15: Add push notifications to website

- apps/tsri/pages/_app.tsx
- libs/membership/website/src/index.ts
- libs/membership/website/src/lib/formatters/format-currency.ts
- libs/membership/website/src/lib/memberplan-picker/memberplan-picker.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-picker/__snapshots__/payment-amount-picker.spec.tsx.snap
- libs/membership/website/src/lib/payment-amount/payment-amount-picker/payment-amount-picker.spec.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-picker/payment-amount-picker.stories.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-picker/payment-amount-picker.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-slider/__snapshots__/payment-amount-slider.spec.tsx.snap
- libs/membership/website/src/lib/payment-amount/payment-amount-slider/payment-amount-slider.spec.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-slider/payment-amount-slider.stories.tsx
- libs/membership/website/src/lib/payment-amount/payment-amount-slider/payment-amount-slider.tsx
- libs/membership/website/src/lib/subscribe/__snapshots__/subscribe.spec.tsx.snap
- libs/membership/website/src/lib/subscribe/subscribe.tsx
- libs/website/builder/src/lib/membership.interface.ts
- libs/website/builder/src/lib/website-builder.context.tsx
- libs/website/src/lib/website.provider.tsx
Optional replacement for slider, slider is default
> feat(website): added payment amount picker

- apps/babanews/next.config.js
- apps/bajour/next.config.js
- apps/demo/next.config.js
- apps/gruppetto/next.config.js
- apps/mannschaft/next.config.js
- apps/onlinereports/next.config.js
- apps/tsri/next.config.js
- apps/website-example/next.config.js
- apps/wnti/next.config.js
- apps/zwoelf/next.config.js
- libs/utils/website/src/lib/next.config.js
Saves around 20kb of gzipped code
> build(websites): run apollo in prod mode

- libs/website/api/src/lib/client.tsx
Leads to re-render bug, will investigate but this makes it properly work for now
> revert(website-api): reusing of client

- libs/api/src/lib/graphql/subscription-public.ts
Imagine the following use case:
User creates a new subscription but doesn't pay it right away. Later going into the profile. Until now the user could extend the unpaid subscription - but this is exactly to be avoided.
The query would have returned no invoice, since cancelled was supposed to be not null. But it actually was null in the database. So the query returned no unpaid or uncanceled invoice, even though there was an unpaid and not cancelled invoice.
> fix(WEP): can extend property must be non-paid and non-canceled

- apps/tsri/pages/_app.tsx
- apps/tsri/src/components/tsri-article-date.tsx
> feat(tsri): add updated at & lower font size

- libs/banner/editor/src/lib/banner-form.tsx
> fix(editor): banner pages not showing

- apps/editor/src/app/routes/polls/pollEditView.tsx
- libs/membership/editor/src/lib/memberplan/memberplan-form.tsx
- libs/ui/editor/src/lib/atoms/comment/commentPreview.tsx
- libs/ui/editor/src/lib/panel/authorEditPanel.tsx
- libs/ui/editor/src/lib/panel/peerEditPanel.tsx
- libs/ui/editor/src/lib/panel/peerProfileEditPanel.tsx
see: https://github.com/ianstormtaylor/slate/issues/4992
> fix(editor): slate-react is not a controlled component anymore

- apps/wnti/deployment.config.json
- apps/wnti/next.config.js
- apps/wnti/pages/_app.tsx
This adds the GTM script to the page. We have also removed the Analytics tag, since the data can now be collected via Google Tag Manager.
> feat(wnti): Add GTM id

- libs/api/prisma/migrations/20241126132734_peer_article_import/migration.sql
> fix(api): delete peer article comments

- libs/api/src/lib/server.ts
see https://github.com/apollographql/apollo-server/issues/7639
> fix(api): apollo memory leak

- apps/editor/src/app/routes/audience/audience-chart.tsx
- apps/editor/src/app/routes/audience/audience-filter.tsx
This fix resolves a display overflow issue on the audience dashboard, ensuring proper layout rendering.
> fix(editor): avoid audience chart overflow

- apps/editor/src/app/locales/de.json
- apps/editor/src/app/locales/en.json
- apps/editor/src/app/locales/fr.json
- apps/editor/src/app/routes/paywall/paywallForm.tsx
> fix(editor): flexible base url for qr code generation

- apps/onlinereports/pages/a/[slug].tsx
- show recent articles independent of the tags assigned to them
- show the 4 most recently published articles
> feat(onlinereport): OR-98 Aktuelle Beiträge/Recent Articles

- apps/onlinereports/locales/deOverridden.json
- apps/onlinereports/src/block-styles/aktuelle-bild.tsx
* always show image caption on mobile in "Das Wort zum Bild"
* show author on :hover. always show it on mobile
> feat(onlinereports): OR-105 always show image caption on mobile in "Das Wort zum Bild"
