packages/api-db-mongodb/src/adapter.ts
packages/api-db-mongodb/src/migration.ts

This PR fixes some missing awaits on async calls form mongoClient. Additionally it also closes the additional database connection which gets created during a migration.

Await mongoClient calls to avoid memory leaks

---

packages/editor/src/client/blocks/types.ts

In a teaser grid if you choose an article (article, peered article or a page) you can overwrite some of the metadata settings. Amongst them you could overwrite the `preTitle`. This PR fixes a bug that didn't save the preTitle.

save preTitel in teaser

---

packages/editor/src/client/routes/pageList.tsx

Fixed #73 Delete-Dialog not disappearing in pageList
The code in `pageList.tsx` tries to query the cache. Since the fetchPolicy was `no-cache` the cache was empty and it threw an error. 
```
// This throws an error, since the cache is empty
const query = cache.readQuery<PageListQuery>({
query: PageListDocument,
variables: listVariables
})
```
If you dont want to use a cache, you can use the `refetch` function returned from `usePageListQuery`.
Or you can change the fetchPolicy to something else, like `cache-and-network`. I am not sure what you prefer.
I changed to the fetchPolicy that was the closest to the one originally used `no-cache`, but a fetchPolicy that would still write to cache so to avoid the error. This way the `cache.readQuery<PageListQuery>(...)` function works and returns …

bug fix - Delete-Dialog not disappearing in pageList

---

package.json

No more eslint warnings on missing return types for React.FCs. Sofar no return type on React.FCs seems the convention in the repo.

config: explicit-module-boundary-types=off

---

packages/api-db-mongodb/src/migration.ts
packages/api/__tests__/specs/__snapshots__/page.ts.snap
packages/api/__tests__/specs/page.ts
packages/api/src/error.ts
packages/api/src/graphql/mutation.private.ts

Fixes WPC-5. This PR makes the slug field for published pages unique. The `publishPage` mutation now checks if there is another published page with the same slug. If so it returns an error.

Unique page slug

---

packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx

In this commit https://github.com/wepublish/wepublish/commit/2d70f0cfb9eecc81299da8933914ae54355ad73f we introduced an error that makes it impossible to focus an input field inside a sub menu (tables, emojis and links) in the editor.

fixed editor focus

---

packages/api-db-mongodb/src/migration.ts
packages/api/src/db/user.ts
packages/api/src/graphql/user.ts

WPC-241. This PR adds two new fields "company" and "address2" to the user address. For the sake of consistency i renamed the field "street" to "address". For this we have a migration but this makes the PR also breaking because if somebody already uses this in a query or mutation they have to change that.

Enhanced User address

---

examples/api/src/index.ts
examples/website/src/shared/route/articleTemplateContainer.tsx
packages/api-db-mongodb/src/db/article.ts
packages/api/__tests__/specs/__snapshots__/user.ts.snap
packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
packages/api/__tests__/utility.ts
packages/api/src/context.ts
packages/api/src/db/article.ts
packages/api/src/events.ts
packages/api/src/graphql/mutation.private.ts
packages/api/src/graphql/mutation.public.ts
packages/api/src/graphql/permissions.ts
packages/api/src/graphql/query.private.ts
packages/api/src/graphql/query.public.ts
packages/api/src/urlAdapter.ts
packages/editor/src/client/api/article.graphql
packages/editor/src/client/api/index.ts
packages/editor/src/client/locales/en.json
packages/editor/src/client/panel/articlePreviewLinkPanel.tsx
packages/editor/src/client/routes/articleList.tsx

WPC-61. This PR introduces a new GraphQL mutation that generates a JWT out of the article ID. This token is then combined with a URL that can be shared with externals. The token have a validation period and will not work afterwards.

Article Preview Links

---

examples/website/src/shared/blocks/richTextBlock/editor/render.tsx

WPC-257. Renders links in the example website correctly again.

fixed links in example website

---

packages/api/src/graphql/peer.ts
packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
packages/editor/src/client/locales/en.json
packages/editor/src/client/panel/peerEditPanel.tsx

- WPC-262: Set the peered data to display & button to save peer only after a token has been entered.
- WPC-263: Setup error handling on token so an unauthenticated token won't log the user out. Further improvements on token validation with WPC-298.

Disable save without peer data and handle errors of invalid tokens

---

README.md

Removing defunct link from heart emoji
Uncertain what the intention for that link was, but it's kinda irritating for a visitor, as it leads to a 404 page

Remove defunct link from green heart emoji

---

packages/api/src/graphql/query.public.ts

WPC-271. This bug fix makes sure that the API always sets publishedAt and updatedAt field when delivering a draft article

Always set updatedAt and publishedAt date

---

packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
packages/editor/src/client/atoms/toolbar.tsx
packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx

WPC-254: In Rich Text editor the link button should indicate whether a selected text includes link format with a blue border around the button. This is consistent with other Rich Text toolbar buttons.

Highlight link button

---

packages/editor/src/client/panel/teaserEditPanel.tsx

WPC-328:  Removes the extra lead field that was in the teaser edit panel.

remove extra lead field from teaser panel

---

packages/editor/src/client/index.tsx

This PR fixes a check in the Editor that doesn't redirect to /logout if the URL path starts with `/login` or `/logout`. The old check failed if the URL continued after `/login`. The URL path `/login/oauth/google?code=123....` failed but is required if we want to login with google or other oauth2 providers.

Proper check if the path includes login or logout

---

examples/website/src/shared/route/articleTemplateContainer.tsx
examples/website/src/shared/route/gqlFragments.ts

This PR removes comments loading from peered articles in the website GraphQL Queries. Comments are not yet peerable.

fix(website): removed comments from graphql query for peer articles

---

examples/api/src/index.ts
examples/website/src/shared/route/routeContext.ts
packages/api/__tests__/utility.ts
packages/api/src/graphql/article.ts
packages/api/src/graphql/query.private.ts
packages/api/src/urlAdapter.ts
packages/editor/src/client/api/article.graphql
packages/editor/src/client/api/index.ts
packages/editor/src/client/locales/en.json
packages/editor/src/client/panel/teaserSelectPanel.tsx

WPC-17 This PR adds a new method to the `URLAdapter` that returns the URL of a peered article. GraphQL will return this url in the `PeerArticle` type and the editor will display it in the Teaser selection list.

Allow previews for peered articles

---

packages/api/src/graphql/query.public.ts

This PR fixes a bug introduced by https://github.com/wepublish/wepublish/pull/305

Page slug can be empty string

---

packages/editor/src/client/panel/publishArticlePanel.tsx
packages/editor/src/client/panel/publishPagePanel.tsx

WPC-566: This fixes the bug where the date picker set the publish date as today when it displayed a future date without selecting.

date fixes on calendar picker

---

packages/api/src/error.ts
packages/api/src/events.ts
packages/api/src/graphql/mutation.public.ts
packages/api/src/utility.ts

This PR introduces a quick way of handling failed registrations. During the registration the user will be created with a temporary mail address. Only after the first successful payment the user will be updated with the correct mail address.

implemented a quick fix for failed registrations

---

examples/api/src/index.ts
packages/api/src/graphql/query.public.ts
packages/api/src/jobs.ts
packages/api/src/memberContext.ts
packages/api/src/payments/paymentProvider.ts

Added new job `dailyInvoiceChecker`  that checks the intent state of all payments on open invoices.
The job `chargeOpenInvoices` now charges open invoices only if the user is active.
The job `dailyInvoiceReminder` only sends mail if the user still exists and is active.
This PR also corrects the calculation for the end date of periods when renewing subscriptions.

Member context improvements

---

packages/api/src/memberContext.ts

The job `checkOpenInvoice` used the paymentMethod of the user.subscription when checking a specific payment. It's now fixed and the job uses the paymentMethod of the payment.

bug fix for checking invoice states

---

packages/api-db-mongodb/src/db/user.ts
packages/api/__tests__/api/public/index.ts
packages/api/src/db/user.ts
packages/api/src/graphql/mutation.public.ts
packages/api/src/memberContext.ts

The model/schema change in #475 did consider the GraphQL filters but not the actual mongodb filters. This PR will fix it.

bug fix for user.subscription.deactivation filters

---

examples/api/src/index.ts
examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentOneWeekBefore/html.pug
examples/api/templates/emails/memberSubscriptionPayment/onSessionAfter/html.pug
examples/api/templates/emails/memberSubscriptionPayment/onSessionBefore/html.pug
packages/api/src/context.ts
packages/api/src/jobs.ts
packages/api/src/memberContext.ts

This PR removes the `userPaymentURL` from the `sendReminderForInvoices` method and adds a loginURL for the subscription reminder mails.

generate loginURL for mails

---

packages/editor/src/client/blocks/types.ts

WPC-650: Flex teasers with page or peer as a teaser weren't saving. This is because in the input type it wasn't set in a teaser.

Save flex teaser of page and peer

---

packages/editor/src/client/api/index.ts
packages/editor/src/client/routes/articleList.tsx
packages/editor/src/client/routes/pageList.tsx

All action buttons are always displayed and disabled when necessary

display action buttons

---

packages/api/src/memberContext.ts

This PR fixes a bug in the `memberContext`. If `parseInt returns `NaN` it should take the right side value. This works with `||` but not with `??`.

send next invoice reminder fix

---

packages/editor/__tests__/specs/unsavedChangesDialog.test.tsx
packages/editor/src/client/unsavedChangesDialog.tsx

The old behaviour was to call useEffect on every single state change, it now only re-calculates the effect when it goes from `false` to `true` and the other way around.

fix(editor): unnecessary recalcs in  useUnsavedChangesDialog

---

packages/api-db-mongodb/src/migration.ts
packages/api/src/events.ts
packages/api/src/server.ts
packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
packages/editor/__tests__/specs/authorEditPanel.tsx
packages/editor/__tests__/specs/peerEditPanel.tsx
packages/editor/__tests__/specs/userEditPanel.tsx
packages/editor/package.json
packages/editor/src/client/atoms/typography.tsx
packages/editor/src/client/base.tsx
packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
packages/editor/src/client/index.tsx
packages/editor/src/client/panel/authorEditPanel.tsx
packages/editor/src/client/panel/userEditPanel.tsx
packages/editor/src/client/routes/peerList.tsx
yarn.lock

A few fixes for ts-ignores, there should be comments to any of the changes.
For the `yarn.lock` changes:
Updating `@types/react` fixes the mismatch between `<root>/node_modules/@types/react` and `<root/packages/editor/node_modules/@types/react`
Updating `@apollo/client` fixes the missmatch between `<root>/packages/editor/node_modules/@apollo/client` and `<root>/packages/editor/node_modules/apollo-upload-client/node_modules/@apollo/client`
While upgrading @apollo/client so that all libraries/dependencies use the same version the tests started to fail.
The errors were that they tried to write a field but it did not exist in the result. This seems to be related to this: https://github.com/apollographql/apollo-client/issues/8677. I don't know if this is a bug by apollo, but it seems like it. …

refactor(api-db-mongodb/api/editor): remove ts-ignores

---

packages/api/src/memberContext.ts

In the memberContext the `sendMail` command should provide the `loginURL` through the data. This way the email templates can work with that loginURL to allow users to be authenticated directly. This already happens in the sendMail for invoice reminders. This PR also generates the `loginURL` for off session mails.

bugfix for missing variable in the sendMail command

---

packages/api/src/graphql/invoice.ts

This PR adds the `canceledAt` field to the graphQL type publicInvoice. Without this field it's not possible to know in the frontend if a invoice has been canceled.

bugfix: added missing canceledAt field in graphQL publicInvoice

---

packages/api-db-mongodb/src/db/invoice.ts

This PR fixes the `getInvoices()` method in the api-db-mongodb adapter. The method arguments and the graphQL query behind it allow for the skip parameter to be passed. But the actual call to the mongo db ignores it.

fix for the mongodb adpater to use the skip function for getInvoices

---

examples/api/package.json
examples/oauth2/package.json
examples/website/package.json
examples/website/src/server/render.tsx
examples/website/src/shared/blocks/peerPageBreak.tsx
packages/api-db-mongodb/package.json
packages/api-media-karma/package.json
packages/api/package.json
packages/api/src/context.ts
packages/api/src/graphql/mutation.public.ts
packages/api/src/graphql/query.public.ts
packages/api/src/mails/MailchimpMailProvider.ts
packages/api/src/mails/mailProvider.ts
packages/api/src/memberContext.ts
packages/api/src/payments/paymentProvider.ts
packages/api/src/payments/stripePaymentProvider.ts
packages/api/src/server.ts
packages/editor/package.json
packages/editor/src/client/panel/peerEditPanel.tsx
packages/editor/src/client/tsconfig.json
packages/oauth2/package.json
yarn.lock

BREAKING CHANGE: Types generated by Typescript 4.x are not compatible with Typescript 3.x

chore: upgraded typescript to latest version

---

packages/api/src/graphql/query.private.ts
packages/api/src/graphql/query.public.ts

WPC-695: fix page query to work with preview token as param without slug.
[Public API](https://api.fwpc695to.wepublish.dev/)
[Private API](https://api.fwpc695to.wepublish.dev/admin)

Preview page with token or slug

---

packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
packages/editor/__tests__/specs/__snapshots__/toggleRequiredLabel.test.ts.snap
packages/editor/__tests__/specs/toggleRequiredLabel.test.ts
packages/editor/src/client/atoms/user/editUserPassword.tsx
packages/editor/src/client/panel/authorEditPanel.tsx
packages/editor/src/client/panel/memberPlanEditPanel.tsx
packages/editor/src/client/panel/paymentMethodEditPanel.tsx
packages/editor/src/client/panel/peerEditPanel.tsx
packages/editor/src/client/panel/peerProfileEditPanel.tsx
packages/editor/src/client/panel/subscriptionEditPanel.tsx
packages/editor/src/client/panel/userRoleEditPanel.tsx
packages/editor/src/client/routes/userEditView.tsx
packages/editor/src/client/toggleRequiredLabel.ts
yarn.lock

Created a new function called toggleRequiredLabel to add the required symbol to labels.
This allows to have an easy way to toggle if it's required or not (adding/editing) and gives us a central way to change the icon if ever desired

fix(editor): editing peers required the token by accident

---

CHANGELOG.md
lerna.json
packages/api-db-mongodb/package.json
packages/api-media-karma/package.json
packages/api/package.json
packages/editor/package.json
packages/oauth2/package.json

* `editor`
* [#649](https://github.com/wepublish/wepublish/pull/649) fix(editor): editing peers required the token by accident ([@Itrulia](https://github.com/Itrulia))
* [#648](https://github.com/wepublish/wepublish/pull/648) ci: upgrade workflows checkout & setup-node + add cache for yarn ([@Itrulia](https://github.com/Itrulia))
- Itrulia ([@Itrulia](https://github.com/Itrulia))

R/release 4.1.1

---

package.json

`docker compose up` doesn't work consistently on all machines. Now changed to `docker-compose up`.

docker compose fix

---

packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
packages/api/prisma/schema.prisma
packages/api/src/graphql/comment/comment.private-mutation.ts
packages/api/src/graphql/comment/comment.ts
packages/api/src/graphql/mutation.private.ts
packages/api/src/graphql/permissions.ts

```graphql
mutation createComment(
$itemID: ID!
$itemType: CommentItemType!
$text: RichText!
$tagIds: [ID!]
) {
createComment(
itemID: $itemID
itemType: $itemType
text: $text
tagIds: $tagIds
) {
id
revisions {
text
}
tags {
id
tag
}
}
}
// vars
{
"itemID": "cl7673h4u1158mspx2rpytjvk",
"itemType": "Article",
"tagIds": ["cl7672l4e0839mspxi0bfzhpc"],
"text": [
{
"type": "paragraph",
"children": [
{
"text": "Haha"
}
]
}
]
}
```
```graphql
mutation updateComment($id: ID!, $text: RichText, $tagIds: [ID!]) {
updateComment(id: $id, text: $text, tagIds: $tagIds) {
id
revisions {
text
}
tags {
id
tag
}
}
}
// vars
{
"id":"cl7679xnq02287fpxggyvj0n4",
"tagIds": ["cl767aneo05387fpx76u8lcwy", "cl7672l4e0839mspxi0bfzhpc"],
"text": [
{
"type": "paragraph",
"children": [
{
"text": "Haha2"
}
]
}
]
}
```

feat(api): allow admins to create and edit comments

---

config/create-gke-manifest.js

```bash
❯ kubectl logs master-postgres-production-654f7764f8-7f27r --namespace=wepublish
W0913 14:03:44.345641   65445 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
postgresql 12:00:53.54
postgresql 12:00:53.56 Welcome to the Bitnami postgresql container
postgresql 12:00:53.56 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:00:53.57 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 12:00:53.57
postgresql 12:00:53.74 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:00:53.78 INFO  ==> Validating settings in POSTGRESQL_* env …
```

ci: use init containers to fix permissions of postgres volume

---

CHANGELOG.md
lerna.json
packages/api-media-karma/package.json
packages/api/__tests__/specs/__snapshots__/navigation.ts.snap
packages/api/__tests__/specs/navigation.ts
packages/api/package.json
packages/api/prisma/migrations/20220823071824_add_relations_navigationlink/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/graphql/user/user.queries.ts
packages/editor/package.json
packages/oauth2/package.json
yarn.lock

* `api-db-mongodb`, `api-media-karma`, `api`, `editor`, `oauth2`
* [#640](https://github.com/wepublish/wepublish/pull/640) Prisma & Postgresql instead of MongoDB ([@Itrulia](https://github.com/Itrulia))
* `api-db-mongodb`, `api-media-karma`, `api`, `editor`, `oauth2`
* [#640](https://github.com/wepublish/wepublish/pull/640) Prisma & Postgresql instead of MongoDB ([@Itrulia](https://github.com/Itrulia))
* [#658](https://github.com/wepublish/wepublish/pull/658) Npm publish only on tags push ([@tomaszdurka](https://github.com/tomaszdurka))
- Itrulia ([@Itrulia](https://github.com/Itrulia))
- Tomasz Durka ([@tomaszdurka](https://github.com/tomaszdurka))
---
BREAKING CHANGE: ArticleList pagination rewritten, now takes a cursor & take argument instead of first/last & before/after. Cursor is not …

Release 5.0.0 (prisma)

---

package.json

automatically regenerates the prisma schema in case you switch branch or merge. Different branches or merges can cause a different schema so one has to regenerate it to fix build issues.

chore: add git hooks to rebuild prisma when switching or merging branches

---

package.json

@Itrulia that's rather irritating feature tbh. Especially as I switch from branch to branch a lot. What about rather having watch command or regenerate with dev command.

Revert "chore: add git hooks to rebuild prisma when switching or merging branches"

---

packages/api/src/graphql/peer-article/peer-article.private-queries.ts

a-b is ASC and b-a is DESC, since we already reverse the order at a later point if order is -1 (DESC) this was sorted the wrong way
Before prisma:
```
if (order === SortOrder.Ascending) {
filtered.reverse()
}
```
After
```
if (order === SortOrder.Descending) {
filtered.reverse()
}
```

fix(api): peer articles sorting is the opposite way

---

packages/api/src/runServer.ts

fixes that vybe articles on bajour for example are linked correctly.

fix(api): use canonical url in runserver if exists for public articles

---

libs/api/prisma/migrations/20230201123630_generate_pending_migrations/migration.sql

This migration does the following:
* Changes the following FKs from ON DELETE CASCADE to RESTRICT
* `articles.revisions.author_authorId_fkey` 
* `articles.revisions.author_revisionId_fkey`
* `articles.revisions.social-media-author_authorId_fkey`
* `articles.revisions.social-media-author_revisionId_fkey`
* Changes the FK `events_imageId_fkey` from ON DELETE CASCADE to SET NULL (since it's nullable)
* Renames the following constraints of the `pages` table to their plural equivalent (e.g. `revisions_*`)
* `revision_pkey`
* `revision_imageID_fkey`
* `revision_socialMediaImageID_fkey`
* Renames the indices of the `pages` table  to their respective equivalent in the plural
* `revision_publishAt_idx`
* `revision_publishedAt_idx`
* `revision_tags_idx`
* `revision_updatedAt_idx`

Generate pending database migrations from manual renames and new prisma library defaults

---

apps/editor/src/app/blocks/richTextBlock/editor/render.tsx
apps/editor/src/app/blocks/richTextBlock/toolbar/tableMenu.tsx

WPC-1024: Tables were only visible when table menu was open, this fixes this issue by moving the tables styling out of the richtext menu into the general tables styles.

bugfix for tables disappearing in richtext block

---

libs/api/src/lib/graphql/action/action.private-queries.ts

WPC-1118: Dashboard action were displaying in wrong order. This fixes where the sort order in the api wasn't working properly.

Display dashboard actions in correct order

---

apps/editor/src/app/base.tsx

WPC-1001: This fixes a bug where extra vertical and horizontal scrollbars appear in the editor when the sidenav menu overflows by having scroll on the navbar itself.

Remove extra scrollbars

---

.eslintrc.json
libs/api/project.json
libs/api/tsconfig.lib.json
libs/authentication/api/project.json
libs/authentication/api/tsconfig.lib.json
libs/consent/api/project.json
libs/consent/api/tsconfig.lib.json
libs/membership/api/project.json
libs/membership/api/tsconfig.lib.json
libs/nest-modules/project.json
libs/permissions/api/project.json
libs/permissions/api/tsconfig.lib.json
libs/settings/api/project.json
libs/settings/api/tsconfig.lib.json
libs/user/api/project.json
libs/user/api/tsconfig.lib.json
package-lock.json
package.json
patches/@nrwl+js+15.3.0.patch

Temporary fix until https://github.com/nrwl/nx/pull/16127 is merged and released

build(js): fix the same library being moved by nx using a patch

---

apps/editor/project.json
docs/README.md
jest.preset.js
libs/api/jest.config.ts
libs/api/project.json
package.json

`nx generate-api editor/api` is now `nx generate-api`

ci: added code coverage & reworked generate commands

---

libs/article/website/src/lib/__snapshots__/article-container.spec.tsx.snap
libs/article/website/src/lib/__snapshots__/article.spec.tsx.snap
libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
libs/block-content/website/src/lib/break/__snapshots__/break-block.spec.tsx.snap
libs/block-content/website/src/lib/break/break-block.tsx
libs/page/website/src/lib/__snapshots__/page-container.spec.tsx.snap
libs/page/website/src/lib/__snapshots__/page.spec.tsx.snap

Made some small improvements to the break block, as the square image was huge on mobile/tablet, spacing was too big on smaller screens etc.
Also changed the reverse to use `order` instead of multiple properties at once

Break Block reverse improvements & smaller screen design improvements

---

libs/consent/api/__tests__/prisma/seed.ts
libs/consent/api/package.json
libs/consent/api/setup-database.js
libs/consent/api/src/lib/consent/consent.model.ts
libs/consent/api/src/lib/consent/consent.resolver.spec.ts
libs/consent/api/src/lib/consent/consent.resolver.ts
libs/consent/api/src/lib/consent/consent.service.spec.ts
libs/consent/api/src/lib/consent/consent.service.ts
libs/consent/api/src/lib/user-consent/user-consent.model.ts
libs/consent/api/src/lib/user-consent/user-consent.resolver.spec.ts
libs/consent/api/src/lib/user-consent/user-consent.resolver.ts
libs/consent/api/src/lib/user-consent/user-consent.service.spec.ts
libs/consent/api/src/lib/user-consent/user-consent.service.ts
libs/consent/editor/src/lib/consent-create-view.tsx
libs/consent/editor/src/lib/consent-edit-view.tsx
libs/consent/editor/src/lib/consent-form.tsx
libs/consent/editor/src/lib/user-consent-create-view.tsx
libs/consent/editor/src/lib/user-consent-edit-view.tsx
libs/consent/editor/src/lib/user-consent-form.tsx

Keeps the API cleaner & more generalized
Also added seeding to not utilize api-example seeding

refactor(consent): use @ArgType instead of @InputType

---

libs/user/website/src/lib/personal-data-form/__snapshots__/personal-data-form-container.stories.spec.tsx.snap
libs/website/api/src/lib/graphql.ts
libs/website/api/src/lib/schemas/image.graphql
package-lock.json
package.json

The media server returns a PNG with a WEBP ending and not actually returning a PNG.
Unlike the other browsers, this breaks Safari in weird ways:
1. It gets insanely slow
2. It breaks the layout

fix(website): use PNG instead of fake WEBP as it breaks safari

---

package.json

Problem was connected with concurrency/parallel option which limits to 3 by default. Instead of increasing the value, decided to not run all the websites for clients

fix(dev): Make sure editor runs in npm run dev, do not run client websites by default

---

libs/api/prisma/run-seed.ts

Create admin user with generated password if not exists
Alternatively if OVERRIDE_ADMIN_PW passed set the password to the value

feat(seeding): Ensure admin user while seeding

---

apps/babanews/pages/[slug].tsx
apps/babanews/pages/a/[slug].tsx
apps/bajour/pages/[slug].tsx
apps/bajour/pages/a/[slug].tsx
apps/bajour/src/components/bajour/archive/archive-slider.tsx
apps/bajour/src/components/bajour/archive/archive.tsx
apps/bajour/src/components/bajour/best-of-wepublish/best-of-wepublish-teaser.tsx
apps/bajour/src/components/website-builder-overwrites/blocks/select-teaser.tsx
apps/bajour/src/components/website-builder-overwrites/blocks/teaser-overwrite.tsx
apps/bajour/src/components/website-builder-overwrites/blocks/teaser-slider/teaser-slide.tsx
apps/bajour/src/components/website-builder-styled/blocks/teaser-grid-styled.tsx
apps/gruppetto/pages/[slug].tsx
apps/gruppetto/pages/_app.tsx
apps/gruppetto/pages/a/[slug].tsx
apps/tsri/pages/[slug].tsx
apps/tsri/pages/a/[slug].tsx
apps/website-example/pages/[slug].tsx
apps/website-example/pages/a/[slug].tsx
libs/article/website/src/lib/__snapshots__/article-container.spec.tsx.snap
libs/article/website/src/lib/__snapshots__/article.spec.tsx.snap
libs/block-content/website/src/lib/__snapshots__/blocks.spec.tsx.snap
libs/block-content/website/src/lib/image/__snapshots__/image-block.spec.tsx.snap
libs/block-content/website/src/lib/image/image-block.tsx
libs/event/website/src/lib/event/__snapshots__/event-container.spec.tsx.snap
libs/event/website/src/lib/event/__snapshots__/event.spec.tsx.snap
libs/membership/website/src/lib/subscription-list/__snapshots__/subscription-list-container.spec.tsx.snap
libs/page/website/src/lib/__snapshots__/page-container.spec.tsx.snap
libs/page/website/src/lib/__snapshots__/page.spec.tsx.snap

1. Bajour didn't want the image cropping, since it caused issues with firefox we reverted it.
2. Fallback set back to blocking as it caused to call the API with null and then with the correct params.
3. Bajour relies on the image in the metadata instead of the image block, overriden for now until further discussion for default behaviour

fix(website): firefox image block issues & fallback to blocking

---

libs/api/__tests__/specs/phrase.test.ts
libs/api/src/lib/graphql/phrase/phrase.public-queries.ts

This is a follow up to WPC-1419 and #1124, where the full text search was improved. The existing code did only replace the first space of the search query with an ampersand. This commit replaces all spaces and makes queries with more than one space possible.

WPC-1419: full text improvements followup

---

libs/api/__tests__/api/public/index.ts
libs/api/__tests__/api/public/phrase.graphql
libs/api/__tests__/specs/phrase.test.ts
libs/api/src/lib/graphql/phrase/phrase.public-queries.ts
libs/api/src/lib/graphql/phrase/phrase.ts
libs/website/api/src/lib/graphql.ts

This adds the values required for pagination to the result of the phrase query. In order to display a pagination component, at least the total number of results is required. A first query is run without any pagination settings applied. This produces a list of ids, and indirectly the total count of matches. For loading the content, another query is run with the pagination and sort orders applied.

WPC-1419: Add page info to full text search

---

apps/editor/__tests__/specs/subscriptionEditView.test.tsx

The snapshots of the SubscriptionEditView were broken because they depended on a date picker that displayed the current date. When running the tests on a date other than 2024-05-21, the rendered DOM was different than the snapshotted version and the tests failed. This change mocks the date to a static date and makes the tests work.

SHARE-10: Make tests independent of current date

---

apps/bajour/src/components/payment-method-picker/payment-method-picker.tsx
apps/editor/src/app/locales/de.json
apps/editor/src/app/locales/en.json
apps/editor/src/app/locales/fr.json
libs/api/src/lib/graphql/blocks.ts
libs/ui/editor/src/lib/panel/linkPageBreakEditPanel.tsx
libs/ui/editor/src/lib/panel/teaserEditPanel.tsx
libs/ui/editor/src/lib/panel/teaserSelectPanel.tsx

Also did the same thing for teasers.
BREAKING CHANGE: Style, template & layout options on break block is deprecated and not editable via the interface anymore. Still accessible through the API for now with deprecation notice.
BREAKING CHANGE: Style options on teasers is deprecated and not editable via the interface anymore. Still accessible through the API for now with deprecation notice.

refactor(api,editor): make style, template & layout options deprecated

---

apps/bajour/pages/_app.tsx
apps/editor/src/app/locales/en.json

The banner was placed in front of the Bajour navigation, because it needed to be in front of the footer. This change moves the navbar one layer to the front.

BA-33: Move nav in front of banner

---

apps/editor/src/app/routes/tags/tagList.tsx

The deletion dialog for the tags should display the name of the tag that is to be deleted. After this change, the dialog displays the tags name instead of [Object object].

fix: display tag name in tag deletion dialog

---

libs/user/website/src/lib/personal-data-form/personal-data-form.tsx

Until we've done with v1/v2 api migration, we cannot upload profile image picture. to avoid constant user feedback un-commented it.

temporarily remove profile picture

---

libs/membership/editor/src/lib/memberplan/memberplan-form.tsx

This pr removes a part of the member plan form, where the migration of subscriptions to a target payment method was displayed twice. Probably due to a merge mistake.

fix(wp): remove migration payment method implemented twice

---

apps/babanews/pages/a/[slug].tsx
apps/babanews/pages/a/preview/[token].tsx
apps/bajour/pages/a/[slug].tsx
apps/bajour/pages/a/preview/[token].tsx
apps/cultur/pages/a/[slug].tsx
apps/cultur/pages/a/preview/[token].tsx
apps/demo/pages/a/[slug].tsx
apps/demo/pages/a/preview/[token].tsx
apps/gruppetto/pages/a/[slug].tsx
apps/gruppetto/pages/a/preview/[token].tsx
apps/mannschaft/pages/a/[slug].tsx
apps/mannschaft/pages/a/preview/[token].tsx
apps/onlinereports/pages/a/[slug].tsx
apps/onlinereports/pages/a/preview/[token].tsx
apps/tsri/pages/a/[slug].tsx
apps/tsri/pages/a/preview/[token].tsx
apps/we-publish/pages/a/[slug].tsx
apps/website-example/pages/a/[slug].tsx
apps/website-example/pages/a/preview/[token].tsx
apps/wnti/pages/a/[slug].tsx
apps/wnti/pages/a/preview/[token].tsx
apps/zwoelf/pages/a/[slug].tsx
apps/zwoelf/pages/a/preview/[token].tsx

As the keys id/token were also sent (token for preview etc) and were potentially undefined,
they also have to be set in the original query for the apollo cache, as else the query variables won't lign up and it can't find it in the cache.

fix(websites): SSR beaking broken (race condition)

---

apps/bajour/src/components/briefing/basel-briefing.tsx

Commit 9ee0bb3275e1f1a75ee14017d7dd7195abe92e7a introduced an unwanted whitespace between the banner and the authors. This removes the whitespaces and reverts to the  existing design.

feat(bajour): Remove whitespace in basel briefing

---

apps/bajour/src/components/search-slider/search-slider.tsx

This commit adds the image credits to the search slider. The currently active image now shows the image source that is defined in the editor.

feat(bajour): Show image credits in search slider

---

apps/wnti/pages/[slug].tsx
apps/wnti/src/theme.tsx
libs/membership/website/src/lib/payment-amount/payment-amount-picker/payment-amount-picker.tsx

The payment picker detected what items to display based on the slug of the payment method. These have changed and the picker must be adapted accordingly.

feat(wnti): Change detection method for payment picker items, theme changes

---

apps/website-example/src/theme.tsx

Only using the nice non-serif font family for the example website. So it's less code and we can show off our site to new media :)

enh(website-example): remove ugly serif font family from website-example

---

libs/article/website/src/lib/article-list/article-list-container.tsx

This change affected more than it intended to as it was meant to just fetch more articles for related articles.
But this:
1. Doesn't work for SSR where it's needed
2. Affects more than just related articles (author pages now load unrelated articles, tag pages, and if your medium doesn't have more than 4 articles it will cause an endless loop).
3. 4 is arbitrary for a general solution
This change also wasn't reviewed as it came in after my approval: https://github.com/wepublish/wepublish/pull/1776/files/8e8615fc5fea102907d17d6de0c3b2ccb62a71ab..85800d5d5c8833e079c1d150cbd80612c665a4e7#diff-0ea864e735d786ab1d732f3f96c51c41c9baa9f5622bc8f5ec852920b9921dcf

revert(website): article list container

---

libs/api/prisma/migrations/20241126132733_migrate_articles_and_pages_to_leave_revision_history/migration.sql

Bajour staging migration failed as there are revisions without page/article.
Since these are zombies we can safely delete them.
Excerpt from logs:
```
2025-03-21 00:15:01.421 GMT [715938] ERROR:  column "articleId" of relation "articles.revisions" contains null values
2025-03-21 00:15:01.421 GMT [715938] STATEMENT:  /*
Warnings:
- You are about to drop the column `draftId` on the `articles` table. All the data in the column will be lost.
- You are about to drop the column `pendingId` on the `articles` table. All the data in the column will be lost.
- You are about to drop the column `publishedId` on the `articles` table. All the data in the column will be lost.
- You are about to drop the column `modifiedAt` on the `articles.revisions` table. All the data in the column will be lost.
- You …
```

fix(api): delete revisions without an article or page

---

apps/flimmer/src/components/tsri-banner.tsx

For longer banner titles, the title overlaps the close button on mobile devices. In those cases, the close button must be moved further into the corner.

feat(flimmer): Move banner close button up and to the right

---

libs/website/api/src/lib/client.tsx

mergeDeepLeft should have been mergeDeepRight. mergeDeepLeft merges from left to right and I interpreted it from merging right into the left object.
I reverted the cache a few weeks back as it caused weird re-renders, this is fixed with mergeDeepRight

fix(website): client cache reimplemented & fixed

---

libs/api/prisma/migrations/20241126132733_migrate_articles_and_pages_to_leave_revision_history/migration.sql

Articles/Pages that were pending during the migration got their `publishedAt` date overwritten

fix(api): publishedAt migration should only run if not null

---

libs/article/api/src/lib/article.service.ts
libs/page/api/src/lib/page.service.ts

If you publish an article in the future and then publish it even later, the publishedAt wasn't updated.
This caused the application to think that the article is published when it's in fact pending

fix(api): article/page might having wrong publishedAt

---

apps/editor/src/app/routes/subscriptions/subscriptionEditView.tsx

The new implementation takes the memberplans centAmount, divides it by 100, and compares it to the subscriptions amount, which is in CHF. Also, the wrongly named `currency` form input is renamed to `monthlyAmount`.

Fix subscription amount validation

---

libs/api/prisma/migrations/20250904071505_make_all_guids_in_the_database_strings/migration.sql
libs/api/prisma/schema.prisma

As figured out by @dsheyp, when one tries to query an id that is not a guid/uuid, the database throws an error.
This is not desired in my opinion in applications like these as we map urls to ids, this keeps the ids being the same structure but with a more loose database type.

refactor(api): make all guids strings on a database level

---

libs/article/api/src/lib/article.service.ts
libs/page/api/src/lib/page.service.ts

Wenn jemand /A/Artikelname statt /a/artikelname aufruft, liefert die API inzwischen zwar dieselbe Seite, aber der Browser bleibt auf der Großschreibweise stehen. Für Google sieht das deshalb wie eine separate URL aus und sie behält den Leerinhalt im Index. SEO-seitig will man so etwas vermeiden und erzwingt daher meist, dass die Adresse selbst auf die „Kleinbuchstaben-Version“ umgeleitet wird – z. B. indem ein CDN wie Cloudflare alle Pfade lowercased oder indem du in Next.js eine Middleware einsetzt, die bei Großbuchstaben einen 301-Redirect auf die kleingeschriebene URL zurückgibt.

fix(api): added insensitive mode to ArticleService and Pageservice

---

apps/api-example/src/nestapp/app.module.ts
libs/api/src/lib/server.ts

https://www.apollographql.com/docs/apollo-server/v3/performance/cache-backends#ensuring-a-bounded-cache
https://www.apollographql.com/docs/kotlin/advanced/persisted-queries
we don't use the persisted query feature so turned that off.

fix(api): bounded cache in admin api
